### ISSUE TITLE
滚动消息的中英文切换问题

### ISSUE THREAD

**Issue by onlyhy** [Sakuyakun/vue-admin-next#3]
你好，seamlessList切换英文失败了

**Comment by onlyhy** [comment]
将数据从data中删除，写到computed中暂时解决了问题 : )

**Comment by onlyhy** [comment]
将数据绑定从data中删除，写到computed中，暂时解决了问题 : )

**Comment by bouquetrender** [comment]
@onlyhy 好的 感谢提醒
